### ISSUE TITLE
Android.mk not found

### ISSUE THREAD

**Issue by bmi6886** [dpa99c/cordova-plugin-hello-c#4]
Hello,

now i get this error while trying to "cordova platform add android".
![screenshot 6](https://user-images.githubusercontent.com/34339193/34677961-0fed8efe-f492-11e7-8d78-15559f5f0bbe.png)

have you changed something?

**Comment by dpa99c** [comment]
Ah, ok. This was caused by 22fec49 which fixes #3 by splitting `Android.mk` into platform-specific versions. I It still needs a default, so I'll add one, which will be the OSX version so you'll still need to run `compile-android.cmd` after installing the plugin if you're developing on Windows.

**Comment by bmi6886** [comment]
Thanks a lot, adding android works but if try to run the project now i get this error:
![screenshot 7](https://user-images.githubusercontent.com/34339193/34678675-20b0c416-f494-11e7-9de5-ff07d88c10e2.png)

**Comment by dpa99c** [comment]
What version of the Cordova Android platform are you using? `cordova-android@6` or `cordova-android@7`? In `@7`, the project structure changed in a backwardly-incompatible way. I just pushed [a commit](https://github.com/dpa99c/cordova-plugin-hello-c/commit/59e961b80db3ca3d2ef5b4835c6d22b8ecc61948) which should make the plugin compatible with both `@6` and `@7`.

**Comment by bmi6886** [comment]
Im using cordova-android@7. I have tried it with the commit but i still get the same error

**Comment by bmi6886** [comment]
I have tried it with cordova-android@6 but get an error as well
![screenshot 8](https://user-images.githubusercontent.com/34339193/34679497-7678f3da-f496-11e7-91db-d833406dad56.png)

**Comment by dpa99c** [comment]
OK, I'm at work now, so I'll have a look later.

**Comment by bmi6886** [comment]
Ok :)

**Comment by bmi6886** [comment]
thx. But i still get the same error.

**Comment by dpa99c** [comment]
Oops, closed by accident...

I've got it working on Windows (see console output below) but only with `cordova-android@6`. It fails for some reason with `cordova-android@7` that I can't pin down right now.

<details>
<summary>console output</summary>

```

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\Git\cordova-plugin-hello-c-test>cordova -v
8.0.0

D:\Git\cordova-plugin-hello-c-test>npm -v
3.10.10

D:\Git\cordova-plugin-hello-c-test>gradle4.bat

D:\Git\cordova-plugin-hello-c-test>set GRADLE_VERSION=4.3.1

D:\Git\cordova-plugin-hello-c-test>set CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=http://services.gradle.org/distributions/gradle-4.3.1-all.zip

D:\Git\cordova-plugin-hello-c-test>cordova platform add android@6
Using cordova-fetch for cordova-android@6
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.4.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-hello-c" in config.xml. Adding it to the project
Installing "cordova-plugin-hello-c" for android
Adding cordova-plugin-hello-c to package.json
Saved plugin info for "cordova-plugin-hello-c" to config.xml
--save flag or autosave detected
Saving android@~6.4.0 into config.xml file ...

D:\Git\cordova-plugin-hello-c-test>cordova build android
ANDROID_HOME=C:\Users\Admin\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_101
Parallel execution with configuration on demand is an incubating feature.
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Parallel execution with configuration on demand is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_7gfznabdmry1nxhgkjvxkdj6m.run(D:\Git\cordova-plugin-hello-c-test\platforms\android\build.gradle:141)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
:preBuild
:CordovaLib:preBuild
:preBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:prepareLintJar
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:generateDebugResValues
:CordovaLib:processDebugManifest
:createDebugCompatibleScreenManifests
:splitsDiscoveryTaskDebug
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugJniLibFolders
:CordovaLib:compileDebugAidl
:CordovaLib:packageDebugRenderscript NO-SOURCE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:preDebugBuild
:CordovaLib:platformAttrExtractor
:compileDebugAidl
:compileDebugRenderscript
:checkDebugManifest
:generateDebugBuildConfig
:generateDebugResources
:mergeDebugResources
:CordovaLib:generateDebugBuildConfig
:CordovaLib:prepareLintJar
:CordovaLib:javaPreCompileDebug
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:compileDebugNdk NO-SOURCE
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNativeLibsWithMergeJniLibsForDebug
:CordovaLib:transformNativeLibsWithStripDebugSymbolForDebug
:CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavac
:processDebugManifest
:processDebugResources
:generateDebugSources
:generateJsonModelDebug
process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
:externalNativeBuildDebug
Build helloc x86_64
Invalid switch - "Git".
[x86_64] SharedLibrary  : libhelloc.so
Build helloc x86
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Invalid switch - "Git".
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
[x86] SharedLibrary  : libhelloc.so
Build helloc arm64-v8a
Invalid switch - "Git".
[arm64-v8a] SharedLibrary  : libhelloc.so
Build helloc armeabi-v7a
Invalid switch - "Git".
[armeabi-v7a] SharedLibrary  : libhelloc.so
:javaPreCompileDebug
:compileDebugJavaWithJavac
:compileDebugSources
:mergeDebugAssets
:transformClassesWithDexBuilderForDebug
:transformDexArchiveWithExternalLibsDexMergerForDebug
:transformDexArchiveWithDexMergerForDebug
:transformNativeLibsWithMergeJniLibsForDebug
:transformNativeLibsWithStripDebugSymbolForDebug
:processDebugJavaRes
:transformResourcesWithMergeJavaResForDebug
:validateSigningDebug
:packageDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL in 5s
49 actionable tasks: 49 executed
Built the following apk(s):
        D:/Git/cordova-plugin-hello-c-test/platforms/android/build/outputs/apk/debug/android-debug.apk

D:\Git\cordova-plugin-hello-c-test>cd plugins\cordova-plugin-hello-c

D:\Git\cordova-plugin-hello-c-test\plugins\cordova-plugin-hello-c>compile-android.cmd
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.
[arm64-v8a] SharedLibrary  : libhelloc.so
[arm64-v8a] Install        : libhelloc.so => libs/arm64-v8a/libhelloc.so
[armeabi-v7a] SharedLibrary  : libhelloc.so
[armeabi-v7a] Install        : libhelloc.so => libs/armeabi-v7a/libhelloc.so
[x86] SharedLibrary  : libhelloc.so
[x86] Install        : libhelloc.so => libs/x86/libhelloc.so
[x86_64] SharedLibrary  : libhelloc.so
[x86_64] Install        : libhelloc.so => libs/x86_64/libhelloc.so

D:\Git\cordova-plugin-hello-c-test\plugins\cordova-plugin-hello-c\src\android>

```

</details>
